---
sidebar: sidebar 
permalink: concept-kubernetes.html 
keywords: kubernetes, k8s, back up kubernetes, back up k8s, discover kubernetes cluster, discover k8s, amazon eks, eks, azure, aks, back up persistent volumes, persistent volumes, kubernetes support, cloud manager 
summary: Astra Trident 是由 NetApp 维护的一个完全受支持的开源项目。Astra Trident 与 Kubernetes 及其永久性卷框架本机集成，可从运行任意 NetApp 存储平台组合的系统无缝配置和管理卷。 
---
= Kubernetes在BlueXP中进行数据管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Trident 是由 NetApp 维护的一个完全受支持的开源项目。Astra Trident 与 Kubernetes 及其永久性卷框架本机集成，可从运行任意 NetApp 存储平台组合的系统无缝配置和管理卷。 link:https://docs.netapp.com/us-en/trident/index.html["了解有关 Trident 的更多信息"^]。



== 功能

使用 link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html["BlueXP"^] (以前称为Cloud Manager)以及使用Trident操作员部署的兼容版本的Astra Trident、您可以：

* 添加和管理Kubernetes集群
* link:./task/task-k8s-manage-trident.html["安装、升级或卸载Astra Trident"]
* link:./task/task-k8s-manage-storage-classes.html["添加和删除存储类"]
* link:./task/task-k8s-manage-persistent-volumes.html["查看永久性卷"]
* link:./task/task-k8s-manage-remove-cluster.html["删除Kubernetes集群"] 从工作空间
* link:./task/task-kubernetes-enable-services.html["激活或查看Cloud Backup"]




== 支持的 Kubernetes 部署

BlueXP支持在以下环境中运行的受管Kubernetes集群：

* link:./requirements/kubernetes-reqs-aws.html["Amazon Elastic Kubernetes Service （ Amazon EKS ）"]
* link:./requirements/kubernetes-reqs-aks.html["Microsoft Azure Kubernetes Service （ AKS ）"]
* link:./requirements/kubernetes-reqs-gke.html["Google Kubernetes Engine （ GKEE ）"]




== 支持的 Astra Trident 部署

Astra Trident的四个最新版本之一 link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["使用Trident操作符部署"^] 为必填项。


NOTE: 使用部署了Astra Trident `tridentctl` 不支持。如果您使用部署了Astra Trident `tridentctl`、您不能使用BlueXP管理Kubernetes集群。您必须  并重新安装 link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["使用Trident运算符"^] 或 link:./task/task-k8s-manage-trident.html["使用BlueXP"]。

您可以直接从BlueXP安装或升级到最新版本的Astra Trident。

link:https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["查看Astra Trident前提条件"^]



== 支持的后端存储

必须在每个Kubernetes集群上安装NetApp Astra Trident、并且必须将Cloud Volumes ONTAP 或Amazon FSx for ONTAP 配置为集群的后端存储。



== 成本

在BlueXP中、_discover_您的Kubernetes集群无需付费、但在使用Cloud Backup Service 备份永久性卷时、您需要付费。
